name: Rust Client Release
on:
  workflow_call:
    secrets:
      CRATES_IO_TOKEN:
        required: true
      ACCESS_TOKEN:
        required: true

jobs:
  check-version:
    name: Check Version
    runs-on: ubuntu-20.04

    outputs:
      local-version: ${{ steps.get-local-version.outputs.version }}
      remote-version: ${{ steps.get-remote-version.outputs.version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Local Version
        id: get-local-version
        working-directory: ./client/rust
        run: echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT

      - name: Get Remote Version
        id: get-remote-version
        run: echo "version=$(curl -s https://pypi.org/pypi/mita_client/json | jq -r '.info.version')" >> $GITHUB_OUTPUT

  test:
    name: Test
    needs: [ "check-version" ]
    if: needs.check-version.outputs.local-version != needs.check-version.outputs.remote-version
    uses: ./.github/workflows/client-rust-test.yml

  release:
    name: Release
    needs: [ test ]
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true

      - uses: katyo/publish-crates@v2
        with:
          path: './client/rust'
          registry-token: ${{ secrets.CRATES_IO_TOKEN }}
