name: Release
on:
  push:
    branches:
      - master

jobs:
  server-release:
    name: Server Release
    uses: ./.github/workflows/server-release.yml

  client-python-release:
    name: Python Client Release
    uses: ./.github/workflows/client-python-release.yml

  client-js-release:
    name: JS Client Release
    uses: ./.github/workflows/client-js-release.yml
