name: Server Test

on:
  workflow_call:

jobs:
  code-style:
    name: Code Style
    uses: ./.github/workflows/sbt.yml
    with:
      cmd: sbt validateCode
      cache-key: sbt-cache-${{ github.sha }}
      cache-path: |
        ~/.sbt
        ~/.ivy2/cache

  unittest:
    name: Unit Test
    needs:
      - "code-style"
    uses: ./.github/workflows/sbt.yml
    with:
      cmd: sbt test
      cache-key: sbt-cache-${{ github.sha }}
      cache-path: |
        ~/.sbt
        ~/.ivy2/cache

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        mode: [development, production]
        include:
          - mode: development
            port: 3000
          - mode: production
            port: 9000
    name: Integration / ${{ matrix.mode }}
    needs:
      - "unittest"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/integration-test/Dockerfile-${{ matrix.mode }}
          tags: mita
          load: true
          push: false

      - name: Run docker image
        run: docker run -p ${{ matrix.port }}:${{ matrix.port }} -d mita

      - name: Setup scala-cli
        uses: VirtusLab/scala-cli-setup@v0.1.4
        with:
          scala-cli-version: 0.1.4

      - name: Wait for application
        working-directory: .github/integration-test
        run: scala-cli test . --server=false --java-opt "-Dapplication.port=${{ matrix.port }}"
        env:
          MITA_GUEST_PASSWORD: "234"
          MITA_PASSWORD: "123456"
