name: Server Test

on:
  workflow_call:

jobs:
  check-code-style:
    name: Code Style
    uses: ./.github/workflows/sbt.yml
    with:
      cmd: sbt validateCode

  unittest:
    name: Unittest
    needs: # Waiting more lightweight checks
      - "check-code-style"
    uses: ./.github/workflows/sbt.yml
    with:
      cmd: sbt test

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        mode: [development, production]
        include:
          - mode: development
            port: 3000
          - mode: production
            port: 9000
    name: Integration / ${{ matrix.mode }}
    needs:
      - "unittest"
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build docker image
        run: docker build -f .github/integration-test/Dockerfile-${{ matrix.mode }} -t mita .

      - name: Run docker image
        run: docker run -p ${{ matrix.port }}:${{ matrix.port }} -d mita

      - name: Setup scala-cli
        uses: VirtusLab/scala-cli-setup@v0.1.4
        with:
          scala-cli-version: 0.1.4

      - name: Wait for application
        working-directory: .github/integration-test
        run: scala-cli test . --server=false --java-opt "-Dapplication.port=${{ matrix.port }}"
        env:
          MITA_GUEST_PASSWORD: "234"
          MITA_PASSWORD: "123456"
